[supervisord]
nodaemon=true
user=root

[program:vnc]
command=/home/vnc/scripts/start-vnc.sh
user=vnc
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:desktop]
command=/home/vnc/scripts/setup-desktop.sh
user=vnc
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
