[supervisord]
nodaemon=true
user=root

[program:vnc]
command=/home/ms/scripts/start-vnc.sh
user=ms
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:android]
command=/home/ms/scripts/start-android.sh
user=ms
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
